### ISSUE TITLE
bug in handling dates from response_json

### ISSUE THREAD

**Issue by pisteps** [hoenie-ams/PyDSWS#1] opened 2018-02-26 09:18 UTC
hi,
looks like there is a bug when converting dates from response_json

try this:
`import PyDSWS`
`ds = PyDSWS.Datastream(username='xxxxx', password='yyyyy')`
`sec = ds.get_data(tickers='S&PCOMP', fields='PI', start='2001-09-05', end='2001-09-15', freq='D')`

the dates before 2001-09-10 are not correct.
i think the problem is this part of "from_json_to_df" :
`d = d[6:16]`

dates before '2001-09-05' have 1 digit less in the json file.
you can fix by replacing:
`d = d[6:16]`
with: 
`d = d[6:-10]`

**Comment by hoenie-ams** [comment] 2018-03-05 13:35
@pisteps , thanks for reporting this issue. I've amended to code as you suggested and the issue is fixed in PyDSWS 0.07.

**Closed as completed by hoenie-ams** 2018-03-05 13:35 UTC

**Comment by ts4nd3** [comment] 2020-06-30 06:59
Hi,

It seems that, as of yesterday, there is a bug when converting dates from response_json

Similar to the previous example the following is coded:

_import PyDSWS as pyDS
ds = pyDS.Datastream(username='xxxxx', password='yyyyy')
sec = ds.get_data(tickers='S&PCOMP', fields='PI', start='2001-09-05', end='2001-09-15', freq='D')_

and the resulting output is:

  _File "C:\ProgramData\Anaconda3\lib\site-packages\PyDSWS\datastream.py", line 102, in get_data
    df = self.from_json_to_df(response)

  File "C:\ProgramData\Anaconda3\lib\site-packages\PyDSWS\datastream.py", line 41, in from_json_to_df
    if response_json['Dates']:

KeyError: 'Dates'_

Not sure why this error is occuring after running soomthly over the past weeks. 
Same error occurs btw for different ticker and date requests.

**Comment by hoenie-ams** [comment] 2020-07-01 07:41
That is strange. Unfortunately I cannot look into it as I currently don't have access to Datastream...

**Comment by hoenie-ams** [comment] 2023-01-25 10:58
FYI: I cannot replicate your issue. This code is working:
```python
sec = ds.get_data(tickers='S&PCOMP', fields='PI', start='2001-09-05', end='2001-09-15', freq='D')
```
